DROP TABLE TBL_USERS;
DROP TABLE TBL_MOVIE_REVIEWS;
DROP TABLE TBL_MOVIE_SHOWTIMES;
DROP TABLE TBL_MOVIES;

CREATE TABLE TBL_USERS (
	USER_ID INTEGER CONSTRAINT USER_PK PRIMARY KEY,
	USER_NAME VARCHAR(20) UNIQUE,
	USER_PASSWORD VARCHAR(20),
	USER_EMAIL VARCHAR(20) UNIQUE,
	USER_FIRSTNAME VARCHAR(20),
	USER_LASTNAME VARCHAR(20),
	USER_STATUS VARCHAR(8)
);

CREATE TABLE TBL_MOVIES (
	MOVIE_ID INTEGER CONSTRAINT MOVIE_ID PRIMARY KEY,
	MOVIE_NAME VARCHAR(100),
	MOVIE_TYPE INTEGER,
	RELEASE_DATE DATE,
	POSTER BLOB,
	GENRE VARCHAR(200),
	DIRECTOR VARCHAR(200),
	SYNOPSIS VARCHAR(2000),
	ACTORS VARCHAR(200),
	AGE_RATING INTEGER
);

CREATE TABLE TBL_MOVIE_REVIEWS (
	REVIEW_ID INTEGER CONSTRAINT REVIEW_ID PRIMARY KEY,
	MOVIE_ID INTEGER CONSTRAINT MOVIE_REVIEW_FK REFERENCES TBL_MOVIES,
	RATING INTEGER CHECK(RATING > 0 AND RATING <= 5)
);

CREATE TABLE TBL_MOVIE_SHOWTIMES (
	SHOWTIME_ID INTEGER CONSTRAINT SHOWTIME_ID PRIMARY KEY,
	MOVIE_ID INTEGER CONSTRAINT MOVIE_RATING_FK REFERENCES TBL_MOVIES,
	SHOWTIME_TIME TIME
);



