DROP TABLE TBL_USERS;
DROP TABLE TBL_CINEMA_AMENITIES;
DROP TABLE TBL_CINEMAS;
DROP TABLE TBL_MOVIE_GENRES;
DROP TABLE TBL_MOVIE_ACTORS;
DROP TABLE TBL_MOVIE_REVIEWS;
DROP TABLE TBL_MOVIE_SHOWTIMES;
DROP TABLE TBL_MOVIES;

CREATE TABLE TBL_USERS (
	USER_ID INTEGER CONSTRAINT USER_PK PRIMARY KEY,
	USER_NAME VARCHAR(25) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_FIRSTNAME VARCHAR(50),
	USER_LASTNAME VARCHAR(50),
	USER_STATUS VARCHAR(8)
);

CREATE TABLE TBL_CINEMAS (
	CINEMA_ID INTEGER CONSTRAINT CINEMA_PK PRIMARY KEY,
	CINEMA_LOCATION VARCHAR(50) NOT NULL,
	CINEMA_CAPACITY INTEGER NOT NULL
);

CREATE TABLE TBL_CINEMA_AMENITIES (
	AMENITY_ID INTEGER CONSTRAINT AMENITY_PK PRIMARY KEY,
	AMENITY_NAME VARCHAR(50) NOT NULL,
	AMENITY_CINEMA INTEGER NOT NULL REFERENCES TBL_CINEMAS(CINEMA_ID)
);

CREATE TABLE TBL_MOVIES (
	MOVIE_ID INTEGER CONSTRAINT MOVIE_ID PRIMARY KEY,
	MOVIE_NAME VARCHAR(100),
	MOVIE_TYPE INTEGER,
	RELEASE_DATE DATE,
	POSTER BLOB,
	GENRE VARCHAR(200),
	DIRECTOR VARCHAR(200),
	SYNOPSIS VARCHAR(2000),
	ACTORS VARCHAR(200),
	AGE_RATING INTEGER
);

CREATE TABLE TBL_MOVIE_REVIEWS (
	REVIEW_ID INTEGER CONSTRAINT REVIEW_ID PRIMARY KEY,
	REVIEW_PARAGRAPH VARCHAR(500),
	MOVIE_ID INTEGER CONSTRAINT MOVIE_REVIEW_FK REFERENCES TBL_MOVIES,
	REVIEW_RATING INTEGER NOT NULL
);

CREATE TABLE TBL_MOVIE_SHOWTIMES (
	SHOWTIME_ID INTEGER CONSTRAINT SHOWTIME_ID PRIMARY KEY,
	MOVIE_ID INTEGER CONSTRAINT MOVIE_RATING_FK REFERENCES TBL_MOVIES,
	SHOWTIME_TIME TIME
);

CREATE TABLE TBL_MOVIE_GENRES (
	GENRE_ID INTEGER CONSTRAINT GENRE_PK PRIMARY KEY,
	GENRE_NAME VARCHAR(100) NOT NULL,
	GENRE_MOVIE INTEGER CONSTRAINT MOVIE_GENRE_FK REFERENCES TBL_MOVIES(MOVIE_ID)
);

CREATE TABLE TBL_MOVIE_ACTORS (
	ACTOR_ID INTEGER CONSTRAINT ACTOR_PK PRIMARY KEY,
	ACTOR_NAME VARCHAR(100) NOT NULL,
	ACTOR_STATUS VARCHAR(10) NOT NULL,
	ACTOR_MOVIE INTEGER CONSTRAINT MOVIE_ACTOR_FK REFERENCES TBL_MOVIES(MOVIE_ID)
);



