SELECT * from TBL_USERS;
SELECT * FROM TBL_CINEMAS;
SELECT * FROM TBL_CINEMA_AMENITIES;
SELECT * from TBL_MOVIES;
SELECT * from TBL_MOVIE_GENRES;
SELECT * FROM TBL_MOVIE_ACTORS;
SELECT * FROM TBL_MOVIE_REVIEWS;
SELECT * FROM TBL_MOVIE_SHOWTIMES;
SELECT * FROM TBL_BOOKINGS;

SELECT * FROM TBL_MOVIES WHERE RELEASE_DATE <= current_date

select * from TBL_BOOKINGS t1,TBL_MOVIE_SHOWTIMES t2,TBL_MOVIES t3
where  t1.MOVIE_SHOWTIME_ID = t2.MOVIE_SHOWTIME_ID and 
		t2.MOVIE_ID = t3.MOVIE_ID