SELECT * from TBL_USERS;
SELECT * FROM TBL_CINEMAS;
SELECT * FROM TBL_CINEMA_AMENITIES;
SELECT * from TBL_MOVIES;
SELECT * from TBL_MOVIE_GENRES;
SELECT * FROM TBL_MOVIE_ACTORS;
SELECT * FROM TBL_MOVIE_REVIEWS;
SELECT * FROM TBL_MOVIE_SHOWTIMES;
SELECT * FROM TBL_BOOKINGS;

SELECT * FROM TBL_MOVIES WHERE RELEASE_DATE <= current_date