DROP TABLE TBL_USERS;

CREATE TABLE TBL_USERS (
	USER_ID INTEGER CONSTRAINT USER_PK PRIMARY KEY,
	USER_NAME VARCHAR(20) UNIQUE,
	USER_PASSWORD VARCHAR(20),
	USER_EMAIL VARCHAR(20) UNIQUE,
	USER_FIRSTNAME VARCHAR(20),
	USER_LASTNAME VARCHAR(20),
	USER_STATUS VARCHAR(8)
);