SELECT * from TBL_USERS;
SELECT * FROM TBL_CINEMAS;
SELECT * FROM TBL_CINEMA_AMENITIES;
SELECT * from TBL_MOVIES;
SELECT * from TBL_MOVIE_GENRES;
SELECT * FROM TBL_MOVIE_ACTORS;
SELECT * FROM TBL_MOVIE_REVIEWS;
SELECT * FROM TBL_MOVIE_SHOWTIMES;
SELECT AVG(CAST(REVIEW_RATING AS FLOAT)) FROM TBL_MOVIE_REVIEWS WHERE MOVIE_ID = 4;
